### ISSUE TITLE
checkProof 500 error

### ISSUE THREAD

**Issue by widePMarvell** [ton-connect/demo-dapp-with-backend#1]
Please check Internal server error during call on checkProof endpoint.

<img width="1792" alt="Screenshot 2023-01-12 at 11 13 36" src="https://user-images.githubusercontent.com/121398841/212052421-afdf7ef6-439e-4902-9806-f4f0315d3d6d.png">

**Comment by akalittle** [comment]
This is still internal server error.
How to test it properly ?
